-- ========================================================
-- StayFlow Smart PG Management System
-- Supabase Migration 1: Core PostgreSQL Schema
-- Compatible with Supabase PostgreSQL 15+
-- ========================================================

-- 1. Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. Trigger function for auto-updating updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TABLE IF NOT EXISTS "announcements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER NOT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "title" varchar(200) NOT NULL,
    "content" text NOT NULL,
    "priority" VARCHAR(50) DEFAULT 'normal',
    "created_by" INTEGER DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "audit_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "user_id" INTEGER DEFAULT NULL,
    "action" varchar(100) NOT NULL,
    "entity_type" varchar(50) NOT NULL,
    "entity_id" varchar(100) DEFAULT NULL,
    "old_values" TEXT   DEFAULT NULL ),
    "new_values" TEXT   DEFAULT NULL ),
    "ip_address" varchar(50) DEFAULT NULL,
    "user_agent" text DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "bed_price_history" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER NOT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "room_id" INTEGER NOT NULL,
    "bed_id" INTEGER NOT NULL,
    "old_price" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "new_price" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "effective_from" date NOT NULL,
    "changed_by" INTEGER DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "beds" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "room_id" INTEGER NOT NULL,
    "bed_number" varchar(20) NOT NULL,
    "status" VARCHAR(50) DEFAULT 'available',
    "monthly_rent" NUMERIC(10,2) NOT NULL DEFAULT 6500.00,
    "current_tenant_id" INTEGER DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "buildings" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER NOT NULL,
    "building_code" varchar(50) NOT NULL,
    "building_name" varchar(200) NOT NULL,
    "property_type" VARCHAR(50) DEFAULT 'co_living',
    "address" text NOT NULL,
    "city" varchar(100) NOT NULL,
    "state" varchar(100) NOT NULL,
    "pincode" varchar(20) NOT NULL,
    "total_floors" INTEGER DEFAULT 1,
    "total_rooms" INTEGER DEFAULT 0,
    "total_beds" INTEGER DEFAULT 0,
    "curfew_time" time DEFAULT '22:30:00',
    "rules_text" text DEFAULT NULL,
    "upi_vpa" varchar(100) DEFAULT 'stanza-pg@okhdfcbank',
    "upi_payee_name" varchar(150) DEFAULT 'Stanza PG Hub',
    "maintenance_charge" NUMERIC(10,2) DEFAULT 300.00,
    "electricity_unit_rate" NUMERIC(10,2) DEFAULT 10.00,
    "late_fee_daily" NUMERIC(10,2) DEFAULT 50.00,
    "invoice_prefix" varchar(20) DEFAULT 'INV',
    "status" VARCHAR(50) DEFAULT 'active',
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "complaints" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "ticket_no" varchar(50) DEFAULT NULL,
    "tenant_id" INTEGER NOT NULL,
    "room_id" INTEGER DEFAULT NULL,
    "title" varchar(200) NOT NULL,
    "description" text NOT NULL,
    "category" VARCHAR(50) DEFAULT 'other',
    "priority" VARCHAR(50) DEFAULT 'medium',
    "status" VARCHAR(50) DEFAULT 'open',
    "idempotency_key" varchar(64) DEFAULT NULL,
    "assigned_to" varchar(150) DEFAULT NULL,
    "attachment" varchar(255) DEFAULT NULL,
    "admin_remarks" text DEFAULT NULL,
    "resolution_notes" text DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "resolved_at" TIMESTAMPTZ DEFAULT NULL,
    "deleted_at" TIMESTAMPTZ DEFAULT NULL,
    "is_deleted" BOOLEAN DEFAULT FALSE,
    "deleted_by" INTEGER DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "custom_plan_features" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "custom_plan_id" INTEGER NOT NULL,
    "feature_id" INTEGER NOT NULL,
    "is_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "monthly_price" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "annual_price" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "custom_subscription_features" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "custom_subscription_id" INTEGER NOT NULL,
    "feature_id" INTEGER NOT NULL,
    "is_enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "custom_subscription_plans" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "plan_code" varchar(50) NOT NULL,
    "plan_name" varchar(150) NOT NULL,
    "description" text DEFAULT NULL,
    "pricing_mode" VARCHAR(50) DEFAULT 'automatic',
    "discount_type" VARCHAR(50) DEFAULT 'none',
    "discount_value" NUMERIC(10,2) DEFAULT 0.00,
    "calculated_monthly_price" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "calculated_annual_price" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "manual_monthly_price" NUMERIC(10,2) DEFAULT NULL,
    "manual_annual_price" NUMERIC(10,2) DEFAULT NULL,
    "final_monthly_price" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "final_annual_price" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "max_buildings" INTEGER NOT NULL DEFAULT 1,
    "max_beds" INTEGER NOT NULL DEFAULT 100,
    "max_staff" INTEGER NOT NULL DEFAULT 3,
    "max_residents" INTEGER NOT NULL DEFAULT 100,
    "currency" varchar(10) DEFAULT 'INR',
    "status" VARCHAR(50) DEFAULT 'active',
    "created_by" INTEGER DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "custom_subscription_templates" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(150) NOT NULL,
    "description" text DEFAULT NULL,
    "price_monthly" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "price_yearly" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "max_buildings" INTEGER NOT NULL DEFAULT 1,
    "max_beds" INTEGER NOT NULL DEFAULT 100,
    "max_staff" INTEGER NOT NULL DEFAULT 3,
    "max_residents" INTEGER NOT NULL DEFAULT 100,
    "features_json" TEXT   DEFAULT NULL ),
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "custom_subscriptions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER NOT NULL,
    "name" varchar(150) NOT NULL,
    "description" text DEFAULT NULL,
    "pricing_mode" VARCHAR(50) DEFAULT 'manual',
    "price_monthly" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "price_yearly" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "billing_cycle" VARCHAR(50) DEFAULT 'monthly',
    "max_buildings" INTEGER NOT NULL DEFAULT 1,
    "max_beds" INTEGER NOT NULL DEFAULT 100,
    "max_staff" INTEGER NOT NULL DEFAULT 3,
    "max_residents" INTEGER NOT NULL DEFAULT 100,
    "status" VARCHAR(50) DEFAULT 'active',
    "start_date" date NOT NULL,
    "end_date" date DEFAULT NULL,
    "standard_price_val" NUMERIC(10,2) DEFAULT NULL,
    "discount_val" NUMERIC(10,2) DEFAULT NULL,
    "internal_notes" text DEFAULT NULL,
    "created_by" INTEGER DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "eb_readings" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "room_id" INTEGER NOT NULL,
    "billing_month" varchar(7) NOT NULL,
    "previous_reading" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "current_reading" NUMERIC(10,2) NOT NULL,
    "units_consumed" NUMERIC(10,2) NOT NULL,
    "rate_per_unit" NUMERIC(8,2) NOT NULL DEFAULT 10.00,
    "total_amount" NUMERIC(10,2) NOT NULL,
    "occupant_count" INTEGER NOT NULL DEFAULT 1,
    "split_amount_per_tenant" NUMERIC(10,2) NOT NULL,
    "reading_date" date NOT NULL,
    "recorded_by" INTEGER DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "email_otps" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER DEFAULT NULL,
    "email" varchar(150) NOT NULL,
    "otp_hash" varchar(255) NOT NULL,
    "purpose" VARCHAR(50) NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "max_attempts" INTEGER NOT NULL DEFAULT 5,
    "verified_at" TIMESTAMPTZ DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "ip_address" varchar(45) DEFAULT NULL,
    "user_agent" varchar(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "features" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "feature_key" varchar(100) NOT NULL,
    "feature_name" varchar(150) NOT NULL,
    "description" text DEFAULT NULL,
    "default_monthly_price" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "default_annual_price" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "category" varchar(50) NOT NULL,
    "icon" varchar(50) DEFAULT 'bi-check-circle-fill',
    "status" varchar(50) DEFAULT 'active',
    "is_active" BOOLEAN DEFAULT TRUE,
    "sort_order" INTEGER DEFAULT 0,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "floors" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER NOT NULL,
    "building_id" INTEGER NOT NULL,
    "floor_number" INTEGER NOT NULL,
    "floor_name" varchar(100) NOT NULL,
    "status" VARCHAR(50) DEFAULT 'active',
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "gate_pass_movements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "gate_pass_id" INTEGER NOT NULL,
    "organization_id" INTEGER NOT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "tenant_id" INTEGER NOT NULL,
    "staff_user_id" INTEGER DEFAULT NULL,
    "staff_name" varchar(100) DEFAULT NULL,
    "action" VARCHAR(50) NOT NULL,
    "previous_status" varchar(50) DEFAULT NULL,
    "new_status" varchar(50) NOT NULL,
    "out_datetime" TIMESTAMPTZ DEFAULT NULL,
    "due_datetime" TIMESTAMPTZ DEFAULT NULL,
    "actual_out_time" TIMESTAMPTZ DEFAULT NULL,
    "actual_return_time" TIMESTAMPTZ DEFAULT NULL,
    "is_late" BOOLEAN DEFAULT FALSE,
    "late_minutes" INTEGER DEFAULT 0,
    "notes" text DEFAULT NULL,
    "ip_address" varchar(45) DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "gatepasses" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "pass_code" varchar(50) NOT NULL,
    "qr_token" varchar(64) DEFAULT NULL,
    "tenant_id" INTEGER NOT NULL,
    "pass_type" VARCHAR(50) DEFAULT 'night_out',
    "out_datetime" TIMESTAMPTZ NOT NULL,
    "expected_in_datetime" TIMESTAMPTZ NOT NULL,
    "actual_out_datetime" TIMESTAMPTZ DEFAULT NULL,
    "actual_return_datetime" TIMESTAMPTZ DEFAULT NULL,
    "out_staff_id" INTEGER DEFAULT NULL,
    "out_staff_name" varchar(100) DEFAULT NULL,
    "return_staff_id" INTEGER DEFAULT NULL,
    "return_staff_name" varchar(100) DEFAULT NULL,
    "is_late" BOOLEAN DEFAULT FALSE,
    "late_minutes" INTEGER DEFAULT 0,
    "overdue_notified" BOOLEAN DEFAULT FALSE,
    "actual_in_datetime" TIMESTAMPTZ DEFAULT NULL,
    "reason" varchar(255) NOT NULL,
    "destination" varchar(255) NOT NULL,
    "parent_alert_sent" BOOLEAN DEFAULT FALSE,
    "status" VARCHAR(50) DEFAULT 'pending',
    "approved_by" INTEGER DEFAULT NULL,
    "approval_remarks" varchar(255) DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "invoices" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "invoice_no" varchar(50) NOT NULL,
    "tenant_id" INTEGER NOT NULL,
    "room_id" INTEGER NOT NULL,
    "bed_id" INTEGER NOT NULL,
    "billing_month" varchar(7) NOT NULL,
    "rent_amount" NUMERIC(10,2) NOT NULL,
    "eb_units" NUMERIC(10,2) DEFAULT 0.00,
    "eb_amount" NUMERIC(10,2) DEFAULT 0.00,
    "maintenance_amount" NUMERIC(10,2) DEFAULT 0.00,
    "food_amount" NUMERIC(10,2) DEFAULT 0.00,
    "laundry_amount" NUMERIC(10,2) DEFAULT 0.00,
    "other_amount" NUMERIC(10,2) DEFAULT 0.00,
    "tax_amount" NUMERIC(10,2) DEFAULT 0.00,
    "subtotal_amount" NUMERIC(10,2) DEFAULT 0.00,
    "late_fee" NUMERIC(10,2) DEFAULT 0.00,
    "discount_amount" NUMERIC(10,2) DEFAULT 0.00,
    "total_amount" NUMERIC(10,2) NOT NULL,
    "paid_amount" NUMERIC(10,2) DEFAULT 0.00,
    "payment_status" VARCHAR(50) DEFAULT 'unpaid',
    "due_date" date NOT NULL,
    "status" VARCHAR(50) DEFAULT 'pending',
    "notes" text DEFAULT NULL,
    "is_custom" BOOLEAN NOT NULL DEFAULT FALSE,
    "custom_title" varchar(255) DEFAULT NULL,
    "line_items_json" TEXT DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "meal_attendance" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "tenant_id" INTEGER NOT NULL,
    "date" date NOT NULL,
    "breakfast" BOOLEAN NOT NULL DEFAULT TRUE,
    "lunch" BOOLEAN NOT NULL DEFAULT TRUE,
    "dinner" BOOLEAN NOT NULL DEFAULT TRUE,
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "meal_menus" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER NOT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "menu_date" date NOT NULL,
    "breakfast_menu" text DEFAULT NULL,
    "lunch_menu" text DEFAULT NULL,
    "dinner_menu" text DEFAULT NULL,
    "breakfast_available" BOOLEAN DEFAULT TRUE,
    "lunch_available" BOOLEAN DEFAULT TRUE,
    "dinner_available" BOOLEAN DEFAULT TRUE,
    "breakfast_cutoff" varchar(10) DEFAULT '07:30',
    "lunch_cutoff" varchar(10) DEFAULT '11:30',
    "dinner_cutoff" varchar(10) DEFAULT '18:30',
    "special_instructions" varchar(255) DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "notification_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "recipient_phone" varchar(20) NOT NULL,
    "type" VARCHAR(50) NOT NULL,
    "template_name" varchar(100) NOT NULL,
    "message_payload" text NOT NULL,
    "status" VARCHAR(50) DEFAULT 'sent',
    "response_data" text DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "notification_recipients" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "notification_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    "is_read" BOOLEAN DEFAULT FALSE,
    "read_at" TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "notifications" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "user_id" INTEGER DEFAULT NULL,
    "recipient_role" varchar(20) NOT NULL DEFAULT 'admin',
    "recipient_user_id" INTEGER DEFAULT NULL,
    "type" varchar(50) NOT NULL,
    "title" varchar(200) NOT NULL,
    "message" text NOT NULL,
    "priority" VARCHAR(50) DEFAULT 'medium',
    "action_url" varchar(255) DEFAULT NULL,
    "reference_type" varchar(50) DEFAULT NULL,
    "reference_id" INTEGER DEFAULT NULL,
    "is_read" BOOLEAN DEFAULT FALSE,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "expires_at" TIMESTAMPTZ DEFAULT NULL,
    "created_by" INTEGER DEFAULT NULL,
    "metadata" TEXT   DEFAULT NULL )
);

CREATE TABLE IF NOT EXISTS "organizations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_code" varchar(50) NOT NULL,
    "company_name" varchar(200) NOT NULL,
    "legal_name" varchar(250) DEFAULT NULL,
    "owner_name" varchar(150) NOT NULL,
    "email" varchar(150) NOT NULL,
    "phone" varchar(20) NOT NULL,
    "address" text DEFAULT NULL,
    "city" varchar(100) DEFAULT NULL,
    "state" varchar(100) DEFAULT NULL,
    "country" varchar(100) DEFAULT 'India',
    "timezone" varchar(100) DEFAULT 'Asia/Kolkata',
    "currency" varchar(10) DEFAULT 'INR',
    "logo" varchar(255) DEFAULT NULL,
    "plan_id" INTEGER DEFAULT NULL,
    "custom_price_monthly" NUMERIC(10,2) DEFAULT NULL,
    "custom_price_yearly" NUMERIC(10,2) DEFAULT NULL,
    "custom_setup_fee" NUMERIC(10,2) DEFAULT NULL,
    "custom_limits_json" text DEFAULT NULL,
    "subscription_end_date" date DEFAULT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    "custom_plan_id" INTEGER DEFAULT NULL,
    "subscription_status" VARCHAR(50) DEFAULT 'trial',
    "trial_start" date DEFAULT NULL,
    "trial_end" date DEFAULT NULL,
    "custom_domain" varchar(200) DEFAULT NULL,
    "branding_json" TEXT   DEFAULT NULL ),
    "referral_code" varchar(50) DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "payments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "payment_no" varchar(50) NOT NULL,
    "invoice_id" INTEGER NOT NULL,
    "tenant_id" INTEGER NOT NULL,
    "amount" NUMERIC(10,2) NOT NULL,
    "payment_mode" VARCHAR(50) DEFAULT 'upi',
    "transaction_reference" varchar(150) DEFAULT NULL,
    "receipt_number" varchar(50) DEFAULT NULL,
    "status" VARCHAR(50) DEFAULT 'verified',
    "transaction_ref" varchar(100) DEFAULT NULL,
    "reconciliation_status" VARCHAR(50) DEFAULT 'matched',
    "payment_date" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "recorded_by" INTEGER DEFAULT NULL,
    "notes" varchar(255) DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "reconciled_by" INTEGER DEFAULT NULL,
    "reconciled_at" TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "permissions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "perm_key" varchar(100) NOT NULL,
    "name" varchar(150) NOT NULL,
    "module" varchar(50) NOT NULL,
    "description" text DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "plan_features" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "plan_id" INTEGER NOT NULL,
    "feature_id" INTEGER NOT NULL,
    "is_enabled" BOOLEAN DEFAULT TRUE,
    "limit_value" varchar(100) DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "plans" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "plan_code" varchar(50) NOT NULL,
    "plan_slug" varchar(100) DEFAULT NULL,
    "name" varchar(100) NOT NULL,
    "description" text DEFAULT NULL,
    "price_monthly" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "price_yearly" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "setup_fee" NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    "currency" varchar(10) DEFAULT 'INR',
    "billing_type" varchar(50) DEFAULT 'flat',
    "display_order" INTEGER DEFAULT 0,
    "is_recommended" BOOLEAN DEFAULT FALSE,
    "is_custom" BOOLEAN NOT NULL DEFAULT FALSE,
    "cta_text" varchar(100) DEFAULT 'Start Free Trial',
    "cta_action" varchar(100) DEFAULT 'whatsapp',
    "trial_enabled" BOOLEAN DEFAULT TRUE,
    "trial_days" INTEGER DEFAULT 14,
    "yearly_discount_pct" INTEGER DEFAULT 15,
    "max_buildings" INTEGER NOT NULL DEFAULT 1,
    "max_rooms" INTEGER NOT NULL DEFAULT -1,
    "max_beds" INTEGER NOT NULL DEFAULT 100,
    "max_staff" INTEGER NOT NULL DEFAULT 3,
    "max_residents" INTEGER NOT NULL DEFAULT 100,
    "max_storage_gb" INTEGER NOT NULL DEFAULT -1,
    "max_api_requests" INTEGER NOT NULL DEFAULT -1,
    "features_json" TEXT   DEFAULT NULL ),
    "status" VARCHAR(50) DEFAULT 'active',
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "poster_analytics" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "poster_id" INTEGER NOT NULL,
    "organization_id" INTEGER DEFAULT NULL,
    "user_id" INTEGER DEFAULT NULL,
    "action_type" VARCHAR(50) NOT NULL,
    "ip_address" varchar(50) DEFAULT NULL,
    "user_agent" varchar(255) DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "promotional_poster_targets" (
    "poster_id" INTEGER NOT NULL,
    "organization_id" INTEGER NOT NULL,
    "PRIMARY" KEY (`poster_id`,`organization_id`)
);

CREATE TABLE IF NOT EXISTS "promotional_posters" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(200) NOT NULL,
    "description" text DEFAULT NULL,
    "image" varchar(255) NOT NULL,
    "mobile_image" varchar(255) DEFAULT NULL,
    "desktop_image" varchar(255) DEFAULT NULL,
    "cta_text" varchar(100) DEFAULT NULL,
    "cta_url" varchar(255) DEFAULT NULL,
    "target_type" VARCHAR(50) DEFAULT 'global',
    "display_location" VARCHAR(50) DEFAULT 'tenant_dashboard',
    "start_at" TIMESTAMPTZ NOT NULL,
    "end_at" TIMESTAMPTZ NOT NULL,
    "status" VARCHAR(50) DEFAULT 'active',
    "priority" INTEGER DEFAULT 0,
    "display_order" INTEGER DEFAULT 0,
    "impressions" INTEGER DEFAULT 0,
    "clicks" INTEGER DEFAULT 0,
    "created_by" INTEGER DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "push_notification_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "notification_id" INTEGER DEFAULT NULL,
    "user_id" INTEGER NOT NULL,
    "subscription_id" INTEGER DEFAULT NULL,
    "title" varchar(255) NOT NULL,
    "body" text NOT NULL,
    "url" varchar(255) DEFAULT NULL,
    "status" VARCHAR(50) NOT NULL DEFAULT 'sent',
    "http_code" INTEGER DEFAULT NULL,
    "provider_response" text DEFAULT NULL,
    "error_message" text DEFAULT NULL,
    "sent_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "push_subscriptions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER NOT NULL,
    "organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "role" varchar(30) NOT NULL DEFAULT 'resident',
    "endpoint" text NOT NULL,
    "endpoint_hash" varchar(64) NOT NULL,
    "p256dh" text NOT NULL,
    "auth" varchar(255) NOT NULL,
    "platform" varchar(50) DEFAULT 'web',
    "browser" varchar(50) DEFAULT NULL,
    "device_name" varchar(100) DEFAULT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "referral_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "referral_id" INTEGER DEFAULT NULL,
    "event_type" varchar(100) NOT NULL,
    "payload_json" TEXT DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "referral_rewards" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "referral_id" INTEGER NOT NULL,
    "referrer_user_id" INTEGER NOT NULL,
    "referrer_org_id" INTEGER NOT NULL,
    "reward_type" varchar(50) DEFAULT 'free_month',
    "reward_value" NUMERIC(10,2) DEFAULT 0.00,
    "duration_months" INTEGER DEFAULT 1,
    "reward_status" VARCHAR(50) DEFAULT 'earned',
    "subscription_id" INTEGER DEFAULT NULL,
    "earned_at" TIMESTAMPTZ DEFAULT NOW(),
    "applied_at" TIMESTAMPTZ DEFAULT NULL,
    "expires_at" TIMESTAMPTZ DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "referrals" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "referrer_user_id" INTEGER NOT NULL,
    "referrer_org_id" INTEGER NOT NULL,
    "referred_user_id" INTEGER NOT NULL,
    "referred_org_id" INTEGER NOT NULL,
    "referral_code" varchar(50) NOT NULL,
    "referral_status" VARCHAR(50) DEFAULT 'pending',
    "registered_at" TIMESTAMPTZ DEFAULT NOW(),
    "qualified_at" TIMESTAMPTZ DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "refresh_tokens" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER NOT NULL,
    "token" varchar(255) NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "resident_login_otps" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "resident_id" INTEGER NOT NULL,
    "tenant_organization_id" INTEGER NOT NULL,
    "email" varchar(150) NOT NULL,
    "otp_hash" varchar(255) NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "attempt_count" INTEGER NOT NULL DEFAULT 0,
    "max_attempts" INTEGER NOT NULL DEFAULT 5,
    "last_sent_at" TIMESTAMPTZ NOT NULL,
    "verified_at" TIMESTAMPTZ DEFAULT NULL,
    "used_at" TIMESTAMPTZ DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "ip_address" varchar(45) DEFAULT NULL,
    "user_agent" varchar(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "role_permissions" (
    "role_id" INTEGER NOT NULL,
    "permission_id" INTEGER NOT NULL,
    "PRIMARY" KEY (`role_id`,`permission_id`)
);

CREATE TABLE IF NOT EXISTS "roles" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "role_code" varchar(50) NOT NULL,
    "name" varchar(100) NOT NULL,
    "description" text DEFAULT NULL,
    "is_system_role" BOOLEAN DEFAULT FALSE,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "rooms" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "floor_id" INTEGER DEFAULT NULL,
    "room_number" varchar(50) NOT NULL,
    "floor" INTEGER NOT NULL DEFAULT 1,
    "room_type" varchar(50) NOT NULL DEFAULT 'double',
    "ac_type" VARCHAR(50) NOT NULL DEFAULT 'AC',
    "total_beds" INTEGER NOT NULL DEFAULT 2,
    "base_rent" NUMERIC(10,2) NOT NULL DEFAULT 6500.00,
    "amenities" text DEFAULT NULL,
    "description" varchar(255) DEFAULT NULL,
    "status" VARCHAR(50) DEFAULT 'available',
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "subscriptions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER NOT NULL,
    "plan_id" INTEGER NOT NULL,
    "custom_plan_id" INTEGER DEFAULT NULL,
    "billing_cycle" VARCHAR(50) DEFAULT 'monthly',
    "amount" NUMERIC(10,2) NOT NULL,
    "status" VARCHAR(50) DEFAULT 'active',
    "start_date" date NOT NULL,
    "end_date" date NOT NULL,
    "next_billing_date" date NOT NULL,
    "payment_method" varchar(50) DEFAULT 'manual',
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "system_settings" (
    "setting_key" varchar(100) NOT NULL,
    "setting_value" text NOT NULL,
    "updated_at" TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT "pk_system_settings" PRIMARY KEY ("setting_key")
);

CREATE TABLE IF NOT EXISTS "tenant_bookings" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "tenant_id" INTEGER NOT NULL,
    "room_id" INTEGER NOT NULL,
    "bed_id" INTEGER NOT NULL,
    "check_in_date" date NOT NULL,
    "check_out_date" date DEFAULT NULL,
    "scheduled_checkout_date" date DEFAULT NULL,
    "checkout_notice_notes" text DEFAULT NULL,
    "deposit_amount" NUMERIC(10,2) NOT NULL DEFAULT 10000.00,
    "deposit_status" VARCHAR(50) DEFAULT 'paid',
    "monthly_rent" NUMERIC(10,2) NOT NULL,
    "status" VARCHAR(50) DEFAULT 'active',
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "active_tenant_uid" INTEGER GENERATED ALWAYS AS (if(`status` = 'active',`tenant_id`,NULL)) VIRTUAL,
    "active_bed_uid" INTEGER GENERATED ALWAYS AS (if(`status` = 'active',`bed_id`,NULL)) VIRTUAL
);

CREATE TABLE IF NOT EXISTS "tenant_entitlement_overrides" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER NOT NULL,
    "feature_id" INTEGER NOT NULL,
    "is_enabled" BOOLEAN DEFAULT TRUE,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "user_building_assignments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER NOT NULL,
    "building_id" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER DEFAULT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "name" varchar(150) NOT NULL,
    "username" varchar(100) DEFAULT NULL,
    "email" varchar(150) DEFAULT NULL,
    "phone" varchar(20) DEFAULT NULL,
    "password" varchar(255) NOT NULL,
    "role" VARCHAR(50) DEFAULT 'tenant',
    "role_id" INTEGER DEFAULT NULL,
    "parent_name" varchar(150) DEFAULT NULL,
    "parent_phone" varchar(20) DEFAULT NULL,
    "emergency_contact" varchar(20) DEFAULT NULL,
    "kyc_type" VARCHAR(50) DEFAULT 'aadhaar',
    "kyc_number" varchar(100) DEFAULT NULL,
    "aadhaar_doc_path" varchar(255) DEFAULT NULL,
    "pan_doc_path" varchar(255) DEFAULT NULL,
    "kyc_document_photo" varchar(255) DEFAULT NULL,
    "kyc_submitted_at" TIMESTAMPTZ DEFAULT NULL,
    "kyc_rejection_reason" text DEFAULT NULL,
    "referral_code" varchar(50) DEFAULT NULL,
    "kyc_status" VARCHAR(50) DEFAULT 'pending',
    "avatar" varchar(255) DEFAULT NULL,
    "status" VARCHAR(50) DEFAULT 'active',
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW(),
    "last_login_at" TIMESTAMPTZ DEFAULT NULL,
    "email_verified_at" TIMESTAMPTZ DEFAULT NULL,
    "password_changed_at" TIMESTAMPTZ DEFAULT NULL,
    "two_factor_enabled" BOOLEAN DEFAULT FALSE,
    "failed_login_attempts" INTEGER DEFAULT 0,
    "locked_until" TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "whatsapp_message_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_id" INTEGER NOT NULL,
    "building_id" INTEGER DEFAULT NULL,
    "resident_id" INTEGER DEFAULT NULL,
    "gate_pass_id" INTEGER DEFAULT NULL,
    "recipient_type" varchar(50) DEFAULT 'parent',
    "recipient_id" INTEGER DEFAULT NULL,
    "recipient_name" varchar(150) NOT NULL,
    "phone_number" varchar(30) NOT NULL,
    "message_type" VARCHAR(50) NOT NULL DEFAULT 'automatic_template',
    "message_text" text NOT NULL,
    "template_name" varchar(100) DEFAULT NULL,
    "sent_by_user_id" INTEGER NOT NULL,
    "sent_by_user_name" varchar(150) NOT NULL,
    "provider" varchar(50) NOT NULL DEFAULT 'meta_cloud_api',
    "provider_message_id" varchar(255) DEFAULT NULL,
    "status" VARCHAR(50) NOT NULL DEFAULT 'SENT',
    "error_message" text DEFAULT NULL,
    "sent_at" TIMESTAMPTZ DEFAULT NULL,
    "delivered_at" TIMESTAMPTZ DEFAULT NULL,
    "read_at" TIMESTAMPTZ DEFAULT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "blogs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(255) NOT NULL,
    "slug" varchar(255) NOT NULL,
    "excerpt" text DEFAULT NULL,
    "content" TEXT DEFAULT NULL,
    "featured_image" varchar(255) DEFAULT NULL,
    "category" varchar(100) DEFAULT 'Property Management',
    "author" varchar(100) DEFAULT 'StayFlow Team',
    "author_avatar" varchar(255) DEFAULT NULL,
    "read_time_min" INTEGER DEFAULT 5,
    "status" VARCHAR(50) DEFAULT 'draft',
    "published_at" TIMESTAMPTZ DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW(),
    "seo_title" varchar(255) DEFAULT NULL,
    "meta_description" text DEFAULT NULL,
    "focus_keyword" varchar(255) DEFAULT NULL,
    "canonical_url" varchar(500) DEFAULT NULL,
    "og_title" varchar(255) DEFAULT NULL,
    "og_description" text DEFAULT NULL,
    "og_image" varchar(255) DEFAULT NULL,
    "robots_index" BOOLEAN DEFAULT TRUE,
    "robots_follow" BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS "whitepapers" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(255) NOT NULL,
    "slug" varchar(255) NOT NULL,
    "badge_text" varchar(150) DEFAULT 'Industry Research',
    "excerpt" text DEFAULT NULL,
    "overview" text DEFAULT NULL,
    "learning_points_json" text DEFAULT NULL,
    "key_takeaways_json" text DEFAULT NULL,
    "content" TEXT DEFAULT NULL,
    "featured_image" varchar(255) DEFAULT NULL,
    "pdf_file" varchar(255) DEFAULT NULL,
    "category" varchar(100) DEFAULT 'Industry Report',
    "author" varchar(100) DEFAULT 'StayFlow Research',
    "status" VARCHAR(50) DEFAULT 'draft',
    "published_at" TIMESTAMPTZ DEFAULT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW(),
    "seo_title" varchar(255) DEFAULT NULL,
    "meta_description" text DEFAULT NULL,
    "focus_keyword" varchar(255) DEFAULT NULL,
    "canonical_url" varchar(500) DEFAULT NULL,
    "og_title" varchar(255) DEFAULT NULL,
    "og_description" text DEFAULT NULL,
    "og_image" varchar(255) DEFAULT NULL,
    "robots_index" BOOLEAN DEFAULT TRUE,
    "robots_follow" BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS "team_members" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(255) NOT NULL,
    "slug" varchar(255) NOT NULL,
    "designation" varchar(255) NOT NULL,
    "department" varchar(100) DEFAULT 'Management',
    "short_bio" text DEFAULT NULL,
    "full_bio" TEXT DEFAULT NULL,
    "profile_image" varchar(255) DEFAULT NULL,
    "email" varchar(255) DEFAULT NULL,
    "phone" varchar(100) DEFAULT NULL,
    "linkedin_url" varchar(255) DEFAULT NULL,
    "facebook_url" varchar(255) DEFAULT NULL,
    "instagram_url" varchar(255) DEFAULT NULL,
    "twitter_url" varchar(255) DEFAULT NULL,
    "github_url" varchar(255) DEFAULT NULL,
    "dribbble_url" varchar(255) DEFAULT NULL,
    "behance_url" varchar(255) DEFAULT NULL,
    "youtube_url" varchar(255) DEFAULT NULL,
    "website_url" varchar(255) DEFAULT NULL,
    "skills" text DEFAULT NULL,
    "experience" text DEFAULT NULL,
    "company_sections_json" TEXT DEFAULT NULL,
    "status" VARCHAR(50) DEFAULT 'published',
    "display_order" INTEGER DEFAULT 0,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW(),
    "seo_title" varchar(255) DEFAULT NULL,
    "meta_description" text DEFAULT NULL,
    "focus_keyword" varchar(255) DEFAULT NULL,
    "canonical_url" varchar(500) DEFAULT NULL,
    "og_title" varchar(255) DEFAULT NULL,
    "og_description" text DEFAULT NULL,
    "og_image" varchar(255) DEFAULT NULL,
    "robots_index" BOOLEAN DEFAULT TRUE,
    "robots_follow" BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS "slug_redirects" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entity_type" varchar(50) NOT NULL,
    "entity_id" INTEGER NOT NULL,
    "old_slug" varchar(255) NOT NULL,
    "new_slug" varchar(255) NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

-- ========================================================
-- 3. Indexes
-- ========================================================
CREATE INDEX IF NOT EXISTS "announcements_idx_ann_org_idx" ON "announcements" (organization_id);
CREATE INDEX IF NOT EXISTS "announcements_idx_ann_building_idx" ON "announcements" (building_id);
CREATE INDEX IF NOT EXISTS "announcements_idx_ann_org_bld_idx" ON "announcements" (organization_id,building_id);
CREATE INDEX IF NOT EXISTS "audit_logs_idx_audit_org_idx" ON "audit_logs" (organization_id);
CREATE INDEX IF NOT EXISTS "audit_logs_idx_audit_action_idx" ON "audit_logs" (action);
CREATE INDEX IF NOT EXISTS "audit_logs_idx_audit_entity_idx" ON "audit_logs" (entity_type,entity_id);
CREATE INDEX IF NOT EXISTS "audit_logs_idx_audit_created_idx" ON "audit_logs" (created_at);
CREATE INDEX IF NOT EXISTS "bed_price_history_idx_bph_org_bed_idx" ON "bed_price_history" (organization_id,bed_id);
CREATE INDEX IF NOT EXISTS "bed_price_history_idx_bph_effective_idx" ON "bed_price_history" (effective_from);
CREATE UNIQUE INDEX IF NOT EXISTS "beds_room_bed_unique_idx" ON "beds" (room_id,bed_number);
CREATE INDEX IF NOT EXISTS "beds_idx_beds_org_bld_status_idx" ON "beds" (organization_id,building_id,status);
CREATE INDEX IF NOT EXISTS "beds_idx_beds_org_room_idx" ON "beds" (organization_id,room_id);
CREATE INDEX IF NOT EXISTS "beds_idx_beds_tenant_idx" ON "beds" (current_tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS "buildings_uk_org_building_code_idx" ON "buildings" (organization_id,building_code);
CREATE INDEX IF NOT EXISTS "buildings_idx_building_org_idx" ON "buildings" (organization_id);
CREATE INDEX IF NOT EXISTS "buildings_idx_bld_org_idx" ON "buildings" (organization_id);
CREATE UNIQUE INDEX IF NOT EXISTS "complaints_uq_complaint_idempotency_idx" ON "complaints" (organization_id,idempotency_key);
CREATE INDEX IF NOT EXISTS "complaints_tenant_id_idx" ON "complaints" (tenant_id);
CREATE INDEX IF NOT EXISTS "complaints_idx_comp_org_status_idx" ON "complaints" (organization_id,status);
CREATE UNIQUE INDEX IF NOT EXISTS "custom_plan_features_uk_custom_plan_feat_idx" ON "custom_plan_features" (custom_plan_id,feature_id);
CREATE INDEX IF NOT EXISTS "custom_plan_features_custom_plan_id_idx" ON "custom_plan_features" (custom_plan_id);
CREATE INDEX IF NOT EXISTS "custom_plan_features_feature_id_idx" ON "custom_plan_features" (feature_id);
CREATE UNIQUE INDEX IF NOT EXISTS "custom_subscription_features_uk_custom_sub_feature_idx" ON "custom_subscription_features" (custom_subscription_id,feature_id);
CREATE INDEX IF NOT EXISTS "custom_subscription_features_custom_subscription_id_idx" ON "custom_subscription_features" (custom_subscription_id);
CREATE INDEX IF NOT EXISTS "custom_subscription_features_feature_id_idx" ON "custom_subscription_features" (feature_id);
CREATE UNIQUE INDEX IF NOT EXISTS "custom_subscription_plans_plan_code_idx" ON "custom_subscription_plans" (plan_code);
CREATE INDEX IF NOT EXISTS "custom_subscription_plans_status_idx" ON "custom_subscription_plans" (status);
CREATE INDEX IF NOT EXISTS "custom_subscription_plans_plan_code_2_idx" ON "custom_subscription_plans" (plan_code);
CREATE INDEX IF NOT EXISTS "custom_subscriptions_organization_id_idx" ON "custom_subscriptions" (organization_id);
CREATE INDEX IF NOT EXISTS "custom_subscriptions_status_idx" ON "custom_subscriptions" (status);
CREATE UNIQUE INDEX IF NOT EXISTS "eb_readings_uniq_room_month_idx" ON "eb_readings" (room_id,billing_month);
CREATE INDEX IF NOT EXISTS "eb_readings_room_id_idx" ON "eb_readings" (room_id);
CREATE INDEX IF NOT EXISTS "eb_readings_idx_eb_org_month_idx" ON "eb_readings" (organization_id,billing_month);
CREATE INDEX IF NOT EXISTS "email_otps_idx_email_purpose_expires_idx" ON "email_otps" (email,purpose,expires_at);
CREATE INDEX IF NOT EXISTS "email_otps_idx_user_id_idx" ON "email_otps" (user_id);
CREATE INDEX IF NOT EXISTS "email_otps_idx_created_at_idx" ON "email_otps" (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS "features_feature_key_idx" ON "features" (feature_key);
CREATE UNIQUE INDEX IF NOT EXISTS "floors_uk_building_floor_idx" ON "floors" (building_id,floor_number);
CREATE INDEX IF NOT EXISTS "floors_organization_id_idx" ON "floors" (organization_id);
CREATE INDEX IF NOT EXISTS "gate_pass_movements_idx_gp_mov_pass_idx" ON "gate_pass_movements" (gate_pass_id);
CREATE INDEX IF NOT EXISTS "gate_pass_movements_idx_gp_mov_org_bld_idx" ON "gate_pass_movements" (organization_id,building_id,created_at);
CREATE INDEX IF NOT EXISTS "gate_pass_movements_idx_gp_mov_tenant_idx" ON "gate_pass_movements" (tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS "gatepasses_pass_code_idx" ON "gatepasses" (pass_code);
CREATE UNIQUE INDEX IF NOT EXISTS "gatepasses_uniq_gp_token_idx" ON "gatepasses" (qr_token);
CREATE INDEX IF NOT EXISTS "gatepasses_tenant_id_idx" ON "gatepasses" (tenant_id);
CREATE INDEX IF NOT EXISTS "gatepasses_idx_gp_org_status_idx" ON "gatepasses" (organization_id,status);
CREATE UNIQUE INDEX IF NOT EXISTS "invoices_invoice_no_idx" ON "invoices" (invoice_no);
CREATE INDEX IF NOT EXISTS "invoices_tenant_id_idx" ON "invoices" (tenant_id);
CREATE INDEX IF NOT EXISTS "invoices_idx_inv_org_status_idx" ON "invoices" (organization_id,status,billing_month);
CREATE INDEX IF NOT EXISTS "invoices_idx_inv_org_tenant_idx" ON "invoices" (organization_id,tenant_id);
CREATE INDEX IF NOT EXISTS "invoices_idx_inv_org_month_idx" ON "invoices" (organization_id,billing_month);
CREATE INDEX IF NOT EXISTS "invoices_idx_inv_tenant_idx" ON "invoices" (tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS "meal_attendance_tenant_date_unique_idx" ON "meal_attendance" (tenant_id,date);
CREATE UNIQUE INDEX IF NOT EXISTS "meal_attendance_uniq_meal_att_tenant_date_idx" ON "meal_attendance" (tenant_id,date);
CREATE INDEX IF NOT EXISTS "meal_attendance_idx_meal_org_date_idx" ON "meal_attendance" (organization_id,date);
CREATE UNIQUE INDEX IF NOT EXISTS "meal_menus_org_bld_date_unique_idx" ON "meal_menus" (organization_id,building_id,menu_date);
CREATE UNIQUE INDEX IF NOT EXISTS "meal_menus_uniq_meal_menu_date_idx" ON "meal_menus" (organization_id,building_id,menu_date);
CREATE INDEX IF NOT EXISTS "meal_menus_idx_menu_date_idx" ON "meal_menus" (menu_date);
CREATE INDEX IF NOT EXISTS "meal_menus_idx_org_date_idx" ON "meal_menus" (organization_id,menu_date);
CREATE UNIQUE INDEX IF NOT EXISTS "notification_recipients_uk_notif_user_idx" ON "notification_recipients" (notification_id,user_id);
CREATE UNIQUE INDEX IF NOT EXISTS "notification_recipients_uniq_notif_user_idx" ON "notification_recipients" (notification_id,user_id);
CREATE INDEX IF NOT EXISTS "notification_recipients_idx_recip_user_idx" ON "notification_recipients" (user_id);
CREATE INDEX IF NOT EXISTS "notifications_idx_notif_org_idx" ON "notifications" (tenant_organization_id);
CREATE INDEX IF NOT EXISTS "notifications_idx_notif_type_idx" ON "notifications" (type);
CREATE INDEX IF NOT EXISTS "notifications_idx_notif_created_idx" ON "notifications" (created_at);
CREATE INDEX IF NOT EXISTS "notifications_idx_notif_tenant_org_idx" ON "notifications" (tenant_organization_id);
CREATE INDEX IF NOT EXISTS "notifications_idx_notif_building_idx" ON "notifications" (building_id);
CREATE INDEX IF NOT EXISTS "notifications_idx_notif_role_user_idx" ON "notifications" (tenant_organization_id,recipient_role,recipient_user_id,is_read);
CREATE UNIQUE INDEX IF NOT EXISTS "organizations_organization_code_idx" ON "organizations" (organization_code);
CREATE UNIQUE INDEX IF NOT EXISTS "organizations_uk_org_ref_code_idx" ON "organizations" (referral_code);
CREATE INDEX IF NOT EXISTS "organizations_plan_id_idx" ON "organizations" (plan_id);
CREATE INDEX IF NOT EXISTS "organizations_idx_org_code_idx" ON "organizations" (organization_code);
CREATE INDEX IF NOT EXISTS "organizations_idx_org_status_idx" ON "organizations" (subscription_status);
CREATE INDEX IF NOT EXISTS "organizations_custom_plan_id_idx" ON "organizations" (custom_plan_id);
CREATE INDEX IF NOT EXISTS "organizations_idx_org_plan_idx" ON "organizations" (plan_id);
CREATE UNIQUE INDEX IF NOT EXISTS "payments_payment_no_idx" ON "payments" (payment_no);
CREATE INDEX IF NOT EXISTS "payments_invoice_id_idx" ON "payments" (invoice_id);
CREATE INDEX IF NOT EXISTS "payments_tenant_id_idx" ON "payments" (tenant_id);
CREATE INDEX IF NOT EXISTS "payments_idx_pay_org_bld_idx" ON "payments" (organization_id,building_id);
CREATE INDEX IF NOT EXISTS "payments_idx_pay_org_tenant_idx" ON "payments" (organization_id,tenant_id);
CREATE INDEX IF NOT EXISTS "payments_idx_pay_org_date_idx" ON "payments" (organization_id,payment_date);
CREATE UNIQUE INDEX IF NOT EXISTS "permissions_perm_key_idx" ON "permissions" (perm_key);
CREATE UNIQUE INDEX IF NOT EXISTS "plan_features_uk_plan_feature_idx" ON "plan_features" (plan_id,feature_id);
CREATE INDEX IF NOT EXISTS "plan_features_feature_id_idx" ON "plan_features" (feature_id);
CREATE UNIQUE INDEX IF NOT EXISTS "plans_plan_code_idx" ON "plans" (plan_code);
CREATE UNIQUE INDEX IF NOT EXISTS "plans_plan_slug_idx" ON "plans" (plan_slug);
CREATE INDEX IF NOT EXISTS "poster_analytics_poster_id_idx" ON "poster_analytics" (poster_id);
CREATE INDEX IF NOT EXISTS "promotional_poster_targets_organization_id_idx" ON "promotional_poster_targets" (organization_id);
CREATE INDEX IF NOT EXISTS "promotional_posters_idx_poster_dates_idx" ON "promotional_posters" (start_at,end_at);
CREATE INDEX IF NOT EXISTS "promotional_posters_idx_poster_status_idx" ON "promotional_posters" (status);
CREATE INDEX IF NOT EXISTS "push_notification_logs_idx_user_id_idx" ON "push_notification_logs" (user_id);
CREATE INDEX IF NOT EXISTS "push_notification_logs_idx_status_idx" ON "push_notification_logs" (status);
CREATE INDEX IF NOT EXISTS "push_notification_logs_idx_sent_at_idx" ON "push_notification_logs" (sent_at);
CREATE UNIQUE INDEX IF NOT EXISTS "push_subscriptions_endpoint_hash_idx" ON "push_subscriptions" (endpoint_hash);
CREATE INDEX IF NOT EXISTS "push_subscriptions_idx_user_id_idx" ON "push_subscriptions" (user_id);
CREATE INDEX IF NOT EXISTS "push_subscriptions_idx_role_idx" ON "push_subscriptions" (role);
CREATE INDEX IF NOT EXISTS "push_subscriptions_idx_is_active_idx" ON "push_subscriptions" (is_active);
CREATE INDEX IF NOT EXISTS "referral_events_idx_re_referral_idx" ON "referral_events" (referral_id);
CREATE INDEX IF NOT EXISTS "referral_events_idx_re_type_idx" ON "referral_events" (event_type);
CREATE INDEX IF NOT EXISTS "referral_rewards_idx_rr_referrer_idx" ON "referral_rewards" (referrer_user_id,referrer_org_id);
CREATE INDEX IF NOT EXISTS "referral_rewards_idx_rr_status_idx" ON "referral_rewards" (reward_status);
CREATE INDEX IF NOT EXISTS "referrals_idx_ref_referrer_idx" ON "referrals" (referrer_user_id,referrer_org_id);
CREATE INDEX IF NOT EXISTS "referrals_idx_ref_referred_idx" ON "referrals" (referred_user_id,referred_org_id);
CREATE INDEX IF NOT EXISTS "referrals_idx_ref_code_idx" ON "referrals" (referral_code);
CREATE UNIQUE INDEX IF NOT EXISTS "refresh_tokens_token_idx" ON "refresh_tokens" (token);
CREATE INDEX IF NOT EXISTS "refresh_tokens_user_id_idx" ON "refresh_tokens" (user_id);
CREATE INDEX IF NOT EXISTS "resident_login_otps_resident_id_idx" ON "resident_login_otps" (resident_id);
CREATE INDEX IF NOT EXISTS "role_permissions_permission_id_idx" ON "role_permissions" (permission_id);
CREATE INDEX IF NOT EXISTS "roles_idx_role_code_idx" ON "roles" (role_code);
CREATE INDEX IF NOT EXISTS "roles_idx_role_org_idx" ON "roles" (organization_id);
CREATE UNIQUE INDEX IF NOT EXISTS "rooms_org_bld_room_unique_idx" ON "rooms" (organization_id,building_id,room_number);
CREATE INDEX IF NOT EXISTS "rooms_idx_rooms_org_bld_idx" ON "rooms" (organization_id,building_id);
CREATE INDEX IF NOT EXISTS "subscriptions_plan_id_idx" ON "subscriptions" (plan_id);
CREATE INDEX IF NOT EXISTS "subscriptions_idx_sub_org_idx" ON "subscriptions" (organization_id);
CREATE INDEX IF NOT EXISTS "subscriptions_custom_plan_id_idx" ON "subscriptions" (custom_plan_id);
CREATE UNIQUE INDEX IF NOT EXISTS "tenant_bookings_uq_tb_active_tenant_idx" ON "tenant_bookings" (organization_id,active_tenant_uid);
CREATE UNIQUE INDEX IF NOT EXISTS "tenant_bookings_uq_tb_active_bed_idx" ON "tenant_bookings" (organization_id,active_bed_uid);
CREATE INDEX IF NOT EXISTS "tenant_bookings_tenant_id_idx" ON "tenant_bookings" (tenant_id);
CREATE INDEX IF NOT EXISTS "tenant_bookings_room_id_idx" ON "tenant_bookings" (room_id);
CREATE INDEX IF NOT EXISTS "tenant_bookings_bed_id_idx" ON "tenant_bookings" (bed_id);
CREATE INDEX IF NOT EXISTS "tenant_bookings_idx_tb_org_status_idx" ON "tenant_bookings" (organization_id,status);
CREATE INDEX IF NOT EXISTS "tenant_bookings_idx_tb_org_tenant_idx" ON "tenant_bookings" (organization_id,tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS "tenant_entitlement_overrides_uk_tenant_feature_idx" ON "tenant_entitlement_overrides" (organization_id,feature_id);
CREATE INDEX IF NOT EXISTS "tenant_entitlement_overrides_feature_id_idx" ON "tenant_entitlement_overrides" (feature_id);
CREATE UNIQUE INDEX IF NOT EXISTS "user_building_assignments_uk_user_building_idx" ON "user_building_assignments" (user_id,building_id);
CREATE INDEX IF NOT EXISTS "user_building_assignments_idx_uba_user_idx" ON "user_building_assignments" (user_id);
CREATE INDEX IF NOT EXISTS "user_building_assignments_idx_uba_building_idx" ON "user_building_assignments" (building_id);
CREATE UNIQUE INDEX IF NOT EXISTS "users_phone_idx" ON "users" (phone);
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_idx" ON "users" (email);
CREATE UNIQUE INDEX IF NOT EXISTS "users_uk_users_ref_code_idx" ON "users" (referral_code);
CREATE INDEX IF NOT EXISTS "users_idx_users_org_role_idx" ON "users" (organization_id,role,status);
CREATE INDEX IF NOT EXISTS "users_idx_users_org_bld_idx" ON "users" (organization_id,building_id);
CREATE INDEX IF NOT EXISTS "users_idx_users_phone_idx" ON "users" (phone);
CREATE INDEX IF NOT EXISTS "whatsapp_message_logs_idx_wml_org_gp_idx" ON "whatsapp_message_logs" (organization_id,gate_pass_id);
CREATE INDEX IF NOT EXISTS "whatsapp_message_logs_idx_wml_gp_idx" ON "whatsapp_message_logs" (gate_pass_id);
CREATE INDEX IF NOT EXISTS "whatsapp_message_logs_idx_wml_res_idx" ON "whatsapp_message_logs" (resident_id);
CREATE INDEX IF NOT EXISTS "whatsapp_message_logs_idx_wml_status_idx" ON "whatsapp_message_logs" (status);
CREATE INDEX IF NOT EXISTS "whatsapp_message_logs_idx_wml_created_idx" ON "whatsapp_message_logs" (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS "blogs_slug_idx" ON "blogs" (slug);
CREATE INDEX IF NOT EXISTS "blogs_idx_status_published_idx" ON "blogs" (status,published_at);
CREATE INDEX IF NOT EXISTS "blogs_idx_slug_idx" ON "blogs" (slug);
CREATE UNIQUE INDEX IF NOT EXISTS "whitepapers_slug_idx" ON "whitepapers" (slug);
CREATE INDEX IF NOT EXISTS "whitepapers_idx_status_published_idx" ON "whitepapers" (status,published_at);
CREATE INDEX IF NOT EXISTS "whitepapers_idx_slug_idx" ON "whitepapers" (slug);
CREATE UNIQUE INDEX IF NOT EXISTS "team_members_slug_idx" ON "team_members" (slug);
CREATE INDEX IF NOT EXISTS "team_members_idx_status_order_idx" ON "team_members" (status,display_order);
CREATE INDEX IF NOT EXISTS "team_members_idx_slug_idx" ON "team_members" (slug);
CREATE UNIQUE INDEX IF NOT EXISTS "slug_redirects_idx_entity_old_slug_idx" ON "slug_redirects" (entity_type,old_slug);
CREATE INDEX IF NOT EXISTS "slug_redirects_idx_lookup_idx" ON "slug_redirects" (entity_type,old_slug);

-- ========================================================
-- 4. Updated_At Triggers
-- ========================================================
DROP TRIGGER IF EXISTS "trg_buildings_updated_at" ON "buildings";
CREATE TRIGGER "trg_buildings_updated_at" BEFORE UPDATE ON "buildings" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_custom_plan_features_updated_at" ON "custom_plan_features";
CREATE TRIGGER "trg_custom_plan_features_updated_at" BEFORE UPDATE ON "custom_plan_features" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_custom_subscription_features_updated_at" ON "custom_subscription_features";
CREATE TRIGGER "trg_custom_subscription_features_updated_at" BEFORE UPDATE ON "custom_subscription_features" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_custom_subscription_plans_updated_at" ON "custom_subscription_plans";
CREATE TRIGGER "trg_custom_subscription_plans_updated_at" BEFORE UPDATE ON "custom_subscription_plans" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_custom_subscription_templates_updated_at" ON "custom_subscription_templates";
CREATE TRIGGER "trg_custom_subscription_templates_updated_at" BEFORE UPDATE ON "custom_subscription_templates" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_custom_subscriptions_updated_at" ON "custom_subscriptions";
CREATE TRIGGER "trg_custom_subscriptions_updated_at" BEFORE UPDATE ON "custom_subscriptions" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_features_updated_at" ON "features";
CREATE TRIGGER "trg_features_updated_at" BEFORE UPDATE ON "features" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_invoices_updated_at" ON "invoices";
CREATE TRIGGER "trg_invoices_updated_at" BEFORE UPDATE ON "invoices" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_meal_attendance_updated_at" ON "meal_attendance";
CREATE TRIGGER "trg_meal_attendance_updated_at" BEFORE UPDATE ON "meal_attendance" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_meal_menus_updated_at" ON "meal_menus";
CREATE TRIGGER "trg_meal_menus_updated_at" BEFORE UPDATE ON "meal_menus" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_organizations_updated_at" ON "organizations";
CREATE TRIGGER "trg_organizations_updated_at" BEFORE UPDATE ON "organizations" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_plan_features_updated_at" ON "plan_features";
CREATE TRIGGER "trg_plan_features_updated_at" BEFORE UPDATE ON "plan_features" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_plans_updated_at" ON "plans";
CREATE TRIGGER "trg_plans_updated_at" BEFORE UPDATE ON "plans" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_promotional_posters_updated_at" ON "promotional_posters";
CREATE TRIGGER "trg_promotional_posters_updated_at" BEFORE UPDATE ON "promotional_posters" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_push_subscriptions_updated_at" ON "push_subscriptions";
CREATE TRIGGER "trg_push_subscriptions_updated_at" BEFORE UPDATE ON "push_subscriptions" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_referrals_updated_at" ON "referrals";
CREATE TRIGGER "trg_referrals_updated_at" BEFORE UPDATE ON "referrals" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_subscriptions_updated_at" ON "subscriptions";
CREATE TRIGGER "trg_subscriptions_updated_at" BEFORE UPDATE ON "subscriptions" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_system_settings_updated_at" ON "system_settings";
CREATE TRIGGER "trg_system_settings_updated_at" BEFORE UPDATE ON "system_settings" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_tenant_entitlement_overrides_updated_at" ON "tenant_entitlement_overrides";
CREATE TRIGGER "trg_tenant_entitlement_overrides_updated_at" BEFORE UPDATE ON "tenant_entitlement_overrides" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_users_updated_at" ON "users";
CREATE TRIGGER "trg_users_updated_at" BEFORE UPDATE ON "users" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_blogs_updated_at" ON "blogs";
CREATE TRIGGER "trg_blogs_updated_at" BEFORE UPDATE ON "blogs" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_whitepapers_updated_at" ON "whitepapers";
CREATE TRIGGER "trg_whitepapers_updated_at" BEFORE UPDATE ON "whitepapers" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS "trg_team_members_updated_at" ON "team_members";
CREATE TRIGGER "trg_team_members_updated_at" BEFORE UPDATE ON "team_members" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ========================================================
-- 5. Foreign Key Constraints (Safe Alter)
-- ========================================================
DO $$ BEGIN
    ALTER TABLE "beds" ADD CONSTRAINT "fk_beds_room_id" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "buildings" ADD CONSTRAINT "fk_buildings_organization_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "complaints" ADD CONSTRAINT "fk_complaints_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "custom_plan_features" ADD CONSTRAINT "fk_custom_plan_features_custom_plan_id" FOREIGN KEY ("custom_plan_id") REFERENCES "custom_subscription_plans" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "custom_plan_features" ADD CONSTRAINT "fk_custom_plan_features_feature_id" FOREIGN KEY ("feature_id") REFERENCES "features" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "eb_readings" ADD CONSTRAINT "fk_eb_readings_room_id" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "floors" ADD CONSTRAINT "fk_floors_organization_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "floors" ADD CONSTRAINT "fk_floors_building_id" FOREIGN KEY ("building_id") REFERENCES "buildings" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "gatepasses" ADD CONSTRAINT "fk_gatepasses_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "invoices" ADD CONSTRAINT "fk_invoices_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "meal_attendance" ADD CONSTRAINT "fk_meal_attendance_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "notification_recipients" ADD CONSTRAINT "fk_notification_recipients_notification_id" FOREIGN KEY ("notification_id") REFERENCES "notifications" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "notification_recipients" ADD CONSTRAINT "fk_notification_recipients_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "organizations" ADD CONSTRAINT "fk_organizations_plan_id" FOREIGN KEY ("plan_id") REFERENCES "plans" ("id") ON DELETE SET NULL ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_invoice_id" FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "plan_features" ADD CONSTRAINT "fk_plan_features_plan_id" FOREIGN KEY ("plan_id") REFERENCES "plans" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "plan_features" ADD CONSTRAINT "fk_plan_features_feature_id" FOREIGN KEY ("feature_id") REFERENCES "features" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "poster_analytics" ADD CONSTRAINT "fk_poster_analytics_poster_id" FOREIGN KEY ("poster_id") REFERENCES "promotional_posters" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "promotional_poster_targets" ADD CONSTRAINT "fk_promotional_poster_targets_poster_id" FOREIGN KEY ("poster_id") REFERENCES "promotional_posters" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "promotional_poster_targets" ADD CONSTRAINT "fk_promotional_poster_targets_organization_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "refresh_tokens" ADD CONSTRAINT "fk_refresh_tokens_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "resident_login_otps" ADD CONSTRAINT "fk_resident_login_otps_resident_id" FOREIGN KEY ("resident_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_role_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_permission_id" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "subscriptions" ADD CONSTRAINT "fk_subscriptions_organization_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "subscriptions" ADD CONSTRAINT "fk_subscriptions_plan_id" FOREIGN KEY ("plan_id") REFERENCES "plans" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "tenant_bookings" ADD CONSTRAINT "fk_tenant_bookings_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "tenant_bookings" ADD CONSTRAINT "fk_tenant_bookings_room_id" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "tenant_bookings" ADD CONSTRAINT "fk_tenant_bookings_bed_id" FOREIGN KEY ("bed_id") REFERENCES "beds" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "tenant_entitlement_overrides" ADD CONSTRAINT "fk_tenant_entitlement_overrides_organization_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE "tenant_entitlement_overrides" ADD CONSTRAINT "fk_tenant_entitlement_overrides_feature_id" FOREIGN KEY ("feature_id") REFERENCES "features" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

